<?php
/**
 * Return the default options of the theme
 * 
 * @return  void
 */

function themesflat_customize_default($key) {
	$default = array(
		'social_links'	=> array ("facebook" => '#', "twitter" => '#', "linkedin2"  => '#', "instagram" => '#'),
		'show_social_share' => 0,		
		'social_footer' => 0,
		'go_top' => 1,
		'logo_controls' => array('padding-top' => '','padding-bottom' => ''),
		'header_backgroundcolor'=>'',
		'style_header'	=> 'header-default',
		'header_sticky' => 0,
		'header_search_box' => 0,
		'header_content_right' => '',
		'header_absolute'	=> 0,		
		'header_socials' => 0,
		'header_socials_label' => '',
		'header_infor_phone' => 0,
		'header_infor_phone_show_email' => 0,
		'header_button' => 1,
		'header_login' => 1,
		'header_button_text' => '<i class="icon-dreamhome-price-house"></i> Sell Property',
		'header_button_url' => '#',
		'header_info_phone_text' => 'Call us:',
		'header_info_phone_icon' => '<i class="icon-dreamhome-phone-call"></i>',
		'header_info_phone_number' => '(201) 555-0124',
		'header_info_email_icon' => '<i class="icon-dreamhome-mail"></i>',
		'header_info_email_label' => 'Email:',
		'header_info_email' => 'Realestatecp@gmail.com',
		'show_post_navigator' => 0,
		'show_entry_footer_content'	=> 0,
		'logo_width' => 197,
		'menu_location_primary' => 'primary',
		'site_logo'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_mobile'	=> THEMESFLAT_LINK . 'images/logo.png',	
		'show_bottom' => 1,		
		'header_backgroundcolor_sticky'=>'#fff',		
		'primary_color'=>'#FFA920',
		'typography_body' => array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'1.5',
		),
		'body_text_color'=>'#3A3A3C',
		'body_background_color' => '',
		'page_sidebar_layout' => 'fullwidth',
		'content_controls' => array('padding-top' => 60,'padding-bottom' => 60),
		'typography_menu' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '16',
			'line_height'=>'70px',
		), 
		'mainnav_color_sticky'		=> '',
		'mainnav_color'		=> '#1C1C1E',
		'mainnav_hover_color'=>'',
		'menu_distance_between' => 10,
		'typography_sub_menu' => array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'24px',
		),
		'sub_nav_color'		=>'',		
		'sub_nav_color_hover'	=>	'',
		'sub_nav_background'=>'#ffffff',
		'sub_nav_background_hover'=>'',
		'sub_nav_border_color' => '#F1F1F1',
		'typography_headings'	=> array(
			'family' => 'Poppins',
			'style'  => '700',
			'line_height'=>'1.2',
		),
		'h1_size' => 45,
		'h2_size' => 30,
		'h3_size' => 18,
		'h4_size' => 16,
		'h5_size' => 14,
		'h6_size' => 12,
		'typography_blockquote' => array(
			'family' => 'Mulish',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'29px',
		),	
		'typography_blog_post_title' => array(
			'family' => 'Poppins',
			'style'  => '700',
			'size'   => '30',
			'line_height'=>'1.5',
		),
		'typography_blog_post_meta' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '13',
			'line_height'=>'1.5384615384615385',
		),
		'typography_blog_post_buttons' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '13',
			'line_height'=>'1.5384615384615385',
		),
		'typography_blog_single_title' => array(
			'family' => 'Poppins',
			'style'  => '700',
			'size'   => '30',
			'line_height'=>'1.5',
		),
		'typography_blog_single_comment_title' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '18',
			'line_height'=>'1.5',
		),
		'typography_sidebar_widget_title' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '18',
			'line_height'=>'1.5',
		),	
		'typography_footer_widget_title' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '18',
			'line_height'=>'1.5',
		),	
		'typography_page_title'	=> array(
			'family' => 'Poppins',
			'style'  => '700',
			'size'   => '30',
			'line_height'=>'1.5',
		),
		'page_title_background_color' => '#fff',
		'page_title_background_color_opacity' => '100',
		'page_title_text_color' => '#000000',		
		'page_title_controls' => array('padding-top' => 30, 'padding-bottom' => 21),
		'page_title_background_image' => '',
		'page_title_image_size' => 'cover',
		'page_title_heading_enabled' => 0,
		'typography_breadcrumb'	=> array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '12',
			'line_height'=>'1.5',
		),
		'bread_crumb_prefix' =>'',
		'breadcrumb_separator' =>  '<i class="icon-dreamhome-angle-right"></i>',
		'breadcrumb_color' => '#8E8E93',
		'typography_buttons' => array(
			'family' => 'Poppins',
			'style'  => '700',
			'size'   => '15',
			'line_height'=>'1.5384615384615385',
		),
		'typography_pagination'	=> array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '16',
			'line_height'=>'1.5',
		),		
		'typography_bottom_menu' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '16',
			'line_height'=>'1.5',
		),
		'breadcrumb_enabled' => 1,
		'show_post_paginator' => 1,
		'blog_grid_columns' => 2,
		'post_content_elements' => 'meta,title,excerpt_content,readmore',
		'meta_elements' => 'date,category',
		'blog_archive_exclude' => '',
		'blog_featured_title' => 'Blog Details',
		'sidebar_layout' => 'sidebar-right',
		'blog_archive_layout' => 'blog-list',
		'blog_sidebar_list'		  => 'blog-sidebar',	
		'blog_layout_single'		  => 'sidebar-right',	
		'blog_archive_readmore' => 1,
		'blog_archive_post_excepts_length' => 25,
		'blog_archive_readmore_text' => 'Read more <i class="dreamhome-arrow-right2"></i>',
		'blog_archive_pagination_style' => 'pager-numeric',
		'blog_posts_per_page'	=> 3,
		'blog_order_by'	=> 'date',
		'blog_order_direction' => 'DESC',
		'page_sidebar_list'	=> 'blog-sidebar',	

		// Property
		
		'property_layout' => 'tfre-sidebar-right',
		'property_sidebar_list' => 'themesflat-custom-sidebar-propertysidebar',
		'property_style_gallery' => 'gallery-style-grid',

		'agent_layout' => 'agent-sidebar-right',

		'feature_form_login' => '',
		'feature_form_register' => '',

		'typography_footer' => array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'22px',
		),
		'footer_background_color'	=> '#1C1C1E',
		'footer_title_widget_color' => '#fff',
		'footer_text_color'			=> 'rgba(229, 229, 229, 1)',
		'footer_text_color_hover'   => '',
		'site_logo_ft'	=> THEMESFLAT_LINK . 'images/logo-white.png',
		'logo_controls_ft' => array('padding-top' => '','padding-bottom' => ''),
		'logo_width_ft' => 197,
		'footer_controls' => array('padding-top' => 100, 'padding-bottom' => 100),
		'footer1' => 'footer-1',
		'footer2' => 'footer-2',
		'footer3' => 'footer-3',
		'footer4' => 'footer-4',
		'tab_footer'   => 0,		
		'show_footer'   => 1,		
		'footer_background_image' => '',
		'footer_image_size' => 'cover',
		'typography_bottom_copyright' => array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'21px',
		),
		'bottom_background_color'	=> '#1C1C1E',
		'bottom_text_color'			=> 'rgba(255, 255, 255, 0.5)',
		'social_bottom'   => 1,		
		'layout_version'			=> 'wide',		
		'footer_copyright'			=> 'Copyright © 2023 Real estate CP. Designed & Developed by <a href="https://themeforest.net/user/themesflat/portfolio">Themesflat</a>',
		'enable_smooth_scroll'	=> 0,
		'enable_preload' => 1,
		'page_title_styles' => 'default',
		'page_title_alignment' => 'left',
		'show_action_box'	=> 0,
		'heading_action_box'	=>	'Our Newsletter',
		'icon_action_box'	=>	'',
		'text_action_box'	=>	'Subscribe to',
		'form_action_box'	=>	'[mc4wp_form id="1999"]',
		'action_box_features_image' =>  THEMESFLAT_LINK . 'images/footer/bg-actionbox.webp',
        'text_button_action_box'	=> '',
        'action_box_image' =>  THEMESFLAT_LINK . 'images/footer/woman.webp',
        'action_box_background_color' => '',
        'action_box_heading_color' => '',
        'action_box_text_color'	=> '',
        'action_box_button_color'	=> '',
        'action_box_button_color_hover' => '',
        'action_box_button_background' => '',
        'action_box_button_background_hover' => '',
		'action_box_button_text' => '<i class="icon-dreamhome-phone"></i> Contact Seller',
		'action_box_button_url' => '#',
		'action_box_text' => 'Find for your dream home and increase your investment opportunities',
		'action_box_desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed tristique metus proin id lorem odio',
        'show_footer_info'	=> 0,
        'show_footer_navigation'	=> 1,
        'show_footer_navigation_menu'	=> 1,
        'show_footer_navigation_social'	=> 1,
        'footer_info_text' => 'You need a house',
        'footer_info_description' => 'Tell us your needs, we will give you thousands of suggestions for the dream home.',
		'footer_info_button_url' => '/contact-us',
        'footer_info_button' => '<i class="icon-dreamhome-phone"></i> Contact Seller',
		'footer_info_image' =>  THEMESFLAT_LINK . 'images/footer/cta-box-1.png',
		'footer_info_text2' => 'Sell your house',
        'footer_info_description2' => 'We will connect you to thousands of people who need to buy a home.',
		'footer_info_button_url2' => '/contact-us',
        'footer_info_button2' => '<i class="icon-dreamhome-price-house"></i> Sell Property',
		'footer_info_image2' =>  THEMESFLAT_LINK . 'images/footer/cta-box-2.png',

		//Dashboard
		'site_logo_dashboard'	=> THEMESFLAT_LINK . 'images/logo-db.png',	

	);
	return $default[$key];
}